### ISSUE TITLE
createTempUser's callback should have three params

### ISSUE THREAD

**Issue by SaintDako** [whitef0x0/node-email-verification#25]
`createTempUser(newUser, callback( err, persistentUser, newTempUser)`

the function already checks for the user being in the persistent collection. if there is a user, then `newTempUser` will just be `null`, but this is ambiguous, as `newTempUser = null` if the user isn't found in the temporary collection.

`persistentUser` should be `null` if the user is NOT found in the persistent collection. makes sense to me :fried_shrimp:

**Comment by MSkaffari** [comment]
I'm able to create new users with the same email in my permanent collection. createTempUser seems to check for existence of the email in temp collection only
