### ISSUE TITLE
user[options.emailFieldName] equates to undefined if email field is nested in another object

### ISSUE THREAD

**Issue by shabbir21** [whitef0x0/node-email-verification#35]
According to the docs:
emailFieldName: the field name for the user's email. If the field is nested within another object(s), use dot notation to access it, e.g. {local: {email: ...}} would use 'local.email'. Required.

but at line 230 of [index.js] in createTempUser function
`query[options.emailFieldName] = user[options.emailFieldName];`
`user[options.emailFieldName]` equates to undefined if email field is nested within another object.

This results in query not returning existing user with the same email and hence it tries to insert the user and unique constraint is violated.

**Comment by whitef0x0** [comment]
Can you elaborate more on how to replicate this error?

**Comment by shabbir21** [comment]
I have a schema and email field is within another object like this : 
`contact:{mobile:String,email:{type:String, unique:true}}`

In nev options i have set email field like this: 
`emailFieldName: 'contact.userName'`

Now when a client signs up, nev tries to look for clients email in temp collection. For that it needs to extract the email value from the user passed to it in createTempUser function. When it tries to get the email value by `user[options.emailFieldName]` it equates to undefined

**Comment by shabbir21** [comment]
Schema and nev configurations attached

[init.txt](https://github.com/SaintDako/node-email-verification/files/257783/init.txt)
[clientProfile.txt](https://github.com/SaintDako/node-email-verification/files/257784/clientProfile.txt)

**Comment by dozzerka** [comment]
**My user schema:**
```
var userSchema = mongoose.Schema( { local : {
    email: String,
    pw: String,
    }
});
```

after changed **emailFieldName** and **passwordFieldName**
```
console.log(newUser);
console.log(newTempUser);

Output: 
{ _id: 57554e878a20a1731c18b997, local: { email: 'testx@gmail.com', pw: '1234' } }
{ __v: 0, _id: 57554e878a20a1731c18b997,
  GENERATED_VERIFYING_URL: 'Px7jHlCX5vg3A0piMZ7k3RcsF8Dik1cBj4WwsJEsBdFgogCi',
  createdAt: Mon Jun 06 2016 13:20:55 GMT+0300 (MSK),
  local: { pw: undefined } }
```

First of all doesnt creating an email field in newTempUser but i have post in my database without them:
```
{ "_id" : ObjectId("57554e878a20a1731c18b997"), "GENERATED_VERIFYING_URL" : "Px7jHlCX5vg3A0piMZ7k3RcsF8Dik1cBj4WwsJEsBdFgogCi", "createdAt" : ISODate("2016-06-06T10:20:55.212Z"), "__v" : 0 }
```

**Comment by shabbir21** [comment]
@dozzerka you must be using `nev.generateTempUserModel(User);` to generate the temporary model. It doesnt work in case your schema has nested objects. Instead making your own temporary model will solve this issue.

**Comment by shabbir21** [comment]
@whitef0x0 
I was able to fix the issue i highlighted earlier.

i changed the below code in index.js file.
```
// create our mongoose query
229    var query = {};
230    query[options.emailFieldName] = user[options.emailFieldName];
231
232    options.persistentUserModel.findOne(query, function(err, existingUser) {
242    options.tempUserModel.findOne(query, function(err, existingTempUser) {
```
by removing line 229 and 230. And change line 232 and 242 as follows:
```
232    options.persistentUserModel.findOne(options.emailFieldName, function(err, existingUser) {
242    options.tempUserModel.findOne(options.emailFieldName, function(err, existingTempUser) {
```

After this it works.

**Comment by whitef0x0** [comment]
@SaintDako merge /fix?

**Comment by whitef0x0** [comment]
@shabbir21 your solution does not make sense considering mongoose's api for findOne

**Comment by whitef0x0** [comment]
This has been fixed in the most recent commit

**Comment by shabbir21** [comment]
@whitef0x0 my bad i pasted the wrong code here.

I used your code as follows:
```
if(options.emailFieldName.split('.').length > 1){
  query[options.emailFieldName] = getNestedValue(user, options.emailFieldName, null);
}else {
  query[options.emailFieldName] = user[options.emailFieldName];
}
```

**Comment by LostInCode404** [comment]
I'm having the same issue. If I `console.log(query);` in the `createTempUser()` method, I get it as `{ local: { email: { undefined: {} } } }`. My schema has `{ local: {email:String, pw:String}}` and I've used `local.email` as the `emailFieldName` in the config. @whitef0x0 , is there a way to fix it without editing the code inside the `email-verification` module(I don't want to be edit that) or I'll have to change it as specified by @shabbir21 .
