### ISSUE TITLE
Nested field for hashing password doesn't work

### ISSUE THREAD

**Issue by melkir** [whitef0x0/node-email-verification#43]
> emailFieldName: the field name for the user's email. If the field is nested within another object(s), use dot notation to access it, e.g. {local: {email: ...}} would use 'local.email'. Required.
passwordFieldName: the field name for the user's password. If the field is nested within another object(s), use dot notation to access it (see above). Required.

It's doesn't work for me, I have "local.password" for my field passwordFieldName and in your insertTempUser (index.js) function you use  
`tempUserData[options.passwordFieldName] = password;`
Which create a field "local.password : blabla" instead of "local : { password : blabla }" so I replaced this line with
`tempUserData.local.password = password;`
but it's not very flexible

**Comment by melkir** [comment]
It should be something like that 
```
var object = {
  baz: {
    foo: {
      bar: 5
    }
  }
};
```
```
object.baz.foo.bar;
object["baz"]["foo"]["bar"];
object["baz"].foo["bar"];
```

**Comment by whitef0x0** [comment]
@melkir right now this is the best way I can think of supported nested object
