### ISSUE TITLE
"Callback is not a function" upon sending confirmation email

### ISSUE THREAD

**Issue by alanplotko** [whitef0x0/node-email-verification#44]
Hello! I'm just checking in to report two instances of the error in the subject on the latest version.

The first time was just a minor issue where the callback for `generateTempUserModel` wasn't mentioned in the sample code in the readme, so adding it stopped the error. Step 3 in the readme uses no callback, but the API at the bottom does. That was my fault, so no worries.

Second time around was for the confirmation email and the trace showed `node_modules/nodemailer-smtp-transport/lib/smtp-transport.js:141`. I was able to get rid of the error by turning off the default option (`shouldSendConfirmation: false`) and then using the following without a callback `nev.sendConfirmationEmail(newPersistentUser['email']);` The API and step 5 both show a callback for the function. Did something perhaps change in nodemailer's end or am I forgetting something important?

Thanks for reading!

**Comment by whitef0x0** [comment]
@alanplotko I'll look into this in more detail

**Comment by whitef0x0** [comment]
@alanplotko sendConfirmationEmail takes a callback

**Comment by alanplotko** [comment]
@whitef0x0 The default is that a confirmation email is sent upon verification (`shouldSendConfirmation = true`), right? Just doing that gives me:

    node_modules/nodemailer-smtp-transport/lib/smtp-transport.js:141
                    return callback(null, info);
                           ^
    TypeError: callback is not a function

Following the example in server.js sends out two emails, and results in the same error. Overriding `shouldSendConfirmation` to false returns it back to one email, and still results in the same error.

Here's my attempt at tracing the problem. I'm using the default option for sending a confirmation and I'm not sending a confirmation email myself (so only one email is sent). The email arrives and all is well, but the app crashes due to the callback issue.

You use `options.shouldSendConfirmation` as a fallback for no callback, which is true in my case (going off the default of true in options). ~Line 340.

    if (options.shouldSendConfirmation) { // true
      if (!callback) { // not specified, !null is true
        callback = options.shouldSendConfirmation; // callback is now set to true
      }
      transporter.sendMail(mailOptions, callback);
    }

Now, nodemailer will handle this by checking callback for a valid function. If true, it will use it. If false, it  will use an empty function. Because it's true, it uses the boolean as opposed to the empty function. ~Line 79.

    if (!callback && typeof Promise === 'function') { // short circuits at !true
        promise = new Promise(function (resolve, reject) {
            callback = callbackPromise(resolve, reject);
        });
    }

    data = data || {};
    data.headers = data.headers || {};
    callback = callback || function () {}; //  callback is set to itself, which is true

Later down the road in the specified area above (smtp-transport.js), it tries to execute callback(null, info). This is great, because it means we successfully sent the email to confirm. However, true is a boolean, not a function. So, it crashes. Perhaps we could set it to an empty function in this node module so that when it trickles down through the steps, it won't crash?

I printed out info, messageId (which is blank strangely), and the callback. It logged twice. The first I got a function, the second came out as true.

```
{ accepted: [ 'EMAIL HERE' ],
  rejected: [],
  response: 'RESPONSE HERE'',
  envelope: 
   { from: 'EMAIL HERE',
     to: [ 'EMAIL HERE' ] },
  messageId: '' }

[Function] // What we want, I believe.
{ accepted: [ 'EMAIL HERE' ],
  rejected: [],
  response: 'RESPONSE HERE'',
  envelope: 
   { from: 'EMAIL HERE',
     to: [ 'EMAIL HERE' ] },
  messageId: '' }

true // Not what we want

```

**Comment by whitef0x0** [comment]
hmmm okok

**Comment by whitef0x0** [comment]
Sound probably add a test case for this as well @frankcash

**Comment by frankcash** [comment]
I can work on doing tests next week :+1:

**Comment by paragverma** [comment]
I'm sort of a beginner in Node. Anyone can explain me how to get around this bug?

**Comment by sahil224** [comment]
where do i need to make the change ? i am not able to find file where the change is to be made at line 340..

**Comment by paragverma** [comment]
The file is index.js in the source folder...

**Comment by sahil224** [comment]
@paragverma  thanks mate... :)

**Comment by Ruegen** [comment]
I'm still getting this issue, I've looked into the index.js to see no change. I get double emails + a crash...

**Comment by whitef0x0** [comment]
@Ruegen @alanplotko this should be fixed now. Sorry about the wait

**Comment by egch** [comment]
it works but I got twice the confirmation mail
