### ISSUE TITLE
NPM Package outdated

### ISSUE THREAD

**Issue by KyoZeus** [whitef0x0/node-email-verification#47]
Ran into this issue with confirmation e-mail, which was receiving "true" as a callback function.
It was easily fixed on commit bb2177933bdb609db7fdff4b0c1d3f2b4729572c, but the NPM package is outdated and doesn't include that change.

**Comment by whitef0x0** [comment]
@KyoZeus I'll update the npm package by this weekend

**Comment by whitef0x0** [comment]
This has been fixed.
