### ISSUE TITLE
Change docs on confirmTempUser

### ISSUE THREAD

**Issue by KyoZeus** [whitef0x0/node-email-verification#48]
confirmTempUser checks your _nev.options.shouldSendConfirmation_, and if it is true, sends a confirmation message. The docs don't mention this, and suggest implementing a _sendConfirmationEmail_ if you wish to send one. This will make the user receive two separate confirmation e-mails.

The docs should include that the user should choose to have _shouldSendConfirmation_ on 'true' or (exclusive) use a _sendConfirmationEmail_ to avoid this issue.

**Comment by whitef0x0** [comment]
Can you submit a PR for this?
