### ISSUE TITLE
getNestedValue undefined bug

### ISSUE THREAD

**Issue by KyoZeus** [whitef0x0/node-email-verification#50]
Bug introduced on commit fe78efc.
The function getNestedValue changed from:
```
var i, len;
for (i = 0, path = path.split('.'), len = path.length; i < len; i++) 
```

to

`for (let i = 0, path = path.split('.'), len = path.length; i < len; i++)`

This change declares 3 lets, "i", "path" and "len". The problem with this is that path is already a defined variable, received as argument of the function, and used in the function.
To solve this problem, you need to either declare the variables "i" and "len" outside the for scope or split the path before the for scope.
I'll submit a pull request with this change later.

**Comment by whitef0x0** [comment]
This has been merged.
