### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by crashspringfield** [whitef0x0/node-email-verification#52]
When I NPM I get the following error:

(node-gyp rebuild 2> builderror.log) || (exit 0)

I've tried some of the suggestions (deleting .node-gyp, making sure no instances of mongod are running) but still get the same error.

**Comment by whitef0x0** [comment]
hmmm

**Comment by whitef0x0** [comment]
What's your OS and node version (run node -v to find out)

**Comment by crashspringfield** [comment]
Mint 17.4, Node 6.5.0

**Comment by whitef0x0** [comment]
@crashspringfield this is an issue with your compiler not to do with this module
