### ISSUE TITLE
TypeError: Temporary user model not defined. Either you forgotto generate one or you did not predefine one.

### ISSUE THREAD

**Issue by mjabraham47** [whitef0x0/node-email-verification#54]
Everything seems to be set up right but it doesn't recognize a temporary user model either generated or predefined.

Any insights?

**Comment by mjabraham47** [comment]
` generated temp user model: true` is showing in my console every time, too

**Comment by whitef0x0** [comment]
@mjabraham47 does mongodb show the generated temp user document?

**Comment by mjabraham47** [comment]
Everything worked out --- I'm using the library successfully. Thanks though!

**Comment by abhilash29** [comment]
@mjabraham47 What fixed the issue?

**Comment by WissemChb** [comment]
@mjabraham47 how did you fix the problem?

**Comment by Keggatron** [comment]
Did anyone ever get this problem solved? I'm having the same issue and would love to know how to fix it. @mjabraham47

**Comment by mjabraham47** [comment]
I don't really remember the problem or what I did, but I'm pasting my code below in the hopes that it helps:

`nev.configure({
    verificationURL: 'http://localhost:3000/users/email-verification/${URL}',
    persistentUserModel: User,
    transportOptions: {
        service: 'Gmail',
        auth: {
            user: 'xxx@gmail.com',
            pass: 'xxx'
        }
    },
    passwordFieldName: 'password',
    hashingFunction: myHasher,
    verifyMailOptions: {
        from: 'Do Not Reply <xxx@gmail.com>',
        subject: 'Please confirm account',
        html: 'Click the following link to confirm your account:</p><p>${URL}</p>',
        text: 'Please confirm your account by clicking the following link: ${URL}'
    }
}, function(error, options){
    if (error) {
        console.log(error);
    }
    nev.generateTempUserModel(User, function(err, tempUserModel) {
            if (err) {
                console.log(err);
                return;
            }
            console.log('generated temp user model: ' + (typeof tempUserModel === 'function'));
    });
});`

`app.post('/create', function(req, res) {
    if (req.body.type === 'register') {
        var email = req.body.email;
        var password = req.body.password;
        var wishlist = req.body.wishlist;
        var newsletter = req.body.newsletter;
        var newUser = new User({
            email: email,
            password: password,
            wishlist: wishlist,
            newsletter: newsletter
        });
        nev.createTempUser(newUser, function(err, existingPersistentUser, newTempUser) {
            if (err) {
                console.log(err);
                return res.status(404).send('ERROR: creating temp user FAILED');
            }
            // user already exists in persistent collection
            if (existingPersistentUser) {
                return res.json({
                    msg: 'You have already signed up and confirmed your account. Did you forget your password?'
                });
            }
            // new user created
            if (newTempUser) {
                var URL = newTempUser[nev.options.URLFieldName];
                nev.sendVerificationEmail(email, URL, function(err, info) {
                    if (err) {
                        return res.status(404).send('ERROR: sending verification email FAILED');
                    }
                    res.json({
                        msg: 'An email has been sent to you. Please check it to verify your account.',
                        info: info
                    });
                });
                // user already exists in temporary collection!
            } else {
                res.json({
                    msg: 'You have already signed up. Please check your email to verify your account.'
                });
            }
        });
    // });
        // resend verification button was clicked
    } else {
        nev.resendVerificationEmail(email, function(err, userFound) {
            if (err) {
                return res.status(404).send('ERROR: resending verification email FAILED');
            }
            if (userFound) {
                res.json({
                    msg: 'An email has been sent to you, yet again. Please check it to verify your account.'
                });
            } else {
                res.json({
                    msg: 'Your verification code has expired. Please sign up again.'
                });
            }
        });
    }
});`

`app.get('/email-verification/:URL', function(req, res) {
    var url = req.params.URL;
    nev.confirmTempUser(url, function(err, user) {
        if (user) {
            nev.sendConfirmationEmail(user.email, function(err, info) {
                if (err) {
                    return res.status(404).send('ERROR: sending confirmation email FAILED');
                }
                res.json({
                    msg: 'CONFIRMED!',
                    info: info
                });
            });
        } else {
            return res.status(404).send('ERROR: confirming temp user FAILED');
        }
    });
});
`
