### ISSUE TITLE
Temporary users does not delete on specified time for Ubuntu 16.04

### ISSUE THREAD

**Issue by SFaubion** [whitef0x0/node-email-verification#55]
On my laptop which has Ubuntu 14.04 the temporary users delete after the correct amount of time. But on my desktop which has Ubuntu 16.04 the delete time for temporary users does not work. I read on MongoDB's site that Ubuntu 16.04 is not fully supported yet. Is there a workaround for this in the mean time, instead of using the key value pair expirationTime: 'key in seconds'?

**Comment by muratsu** [comment]
Where did you read this exactly? Mongodb 3.2+ should be supporting Ubuntu 16.04.

**Comment by SFaubion** [comment]
I don't remember, I'm using Ubuntu vs 14.04 and am still having issues with the specified deletion time. It's still supposed to be in seconds right?

**Comment by SFaubion** [comment]
Figured it out, I had to log into the mongo shell and do db.temporary_users.drop() to change the settings for that collection
