### ISSUE TITLE
API function to validate URL parameter

### ISSUE THREAD

**Issue by gustavomassa** [whitef0x0/node-email-verification#58]
Hello, 

First of all, excellent job, your library is really useful.

We need public route to verify the account and receive the token(generated url) to validate the account. I created a html page and I`m receiving the url token by parameter, but I would like to validate the url token before consulting the validation rest service. Now I`m using the "URLLength" option to validate it. 
What you think about creating a new function just to validate the generated url token? If anyone discover the html verification route and try to use it wrongly( or hack), the page will be protected by the url validation.

Another issue:
```
nev.confirmTempUser(url, function(err, user) {
    if (err)
        // handle error...

    // user was found!
    if (user) {
        // optional
        nev.sendConfirmationEmail(user['email_field_name'], function(err, info) {
            // redirect to their profile...
        });
    }

    // user's data probably expired...
    else
        // redirect to sign-up
});
```

On the else (user's data probably expired) we need to check if user account is already verified, but I can't check it without the decryption of the url token to get the user email.
We need to test if the token is really expired or if user already verified the account, otherwise when user already verified the account and clicks again on the verification link it will say that token is expired and user could not verify the account..

Thank you,
Regards

**Comment by whitef0x0** [comment]
@gustavomassa what do you mean by the decryption of the url token?

**Comment by gustavomassa** [comment]
@whitef0x0  
Lets say I receive the url token on my angular controller, now I need to check if that url is already activated, so I need get the user email that is inside the url token.
Why I need to check it? Because the user has the verification email with the link and he can click on the verification link how many times he want, so I need to check if the account is already verified and return the correct error.

**Comment by whitef0x0** [comment]
you mean unhashing the url hash
