### ISSUE TITLE
Feature to re-verify current users request to update email.

### ISSUE THREAD

**Issue by doubleUTF** [whitef0x0/node-email-verification#61]
I'm looking at the API and wondering if there is a method to update an existing user's email and require double-opt in for that as well. Since this only touches the permanent user model and not the temporary one, will this require a new method such as `nev.sendNewVerificationEmail(newEmail,oldEmail, url, callback(err,info))`?

**Comment by whitef0x0** [comment]
@doubleUTF there is no such method yet, but PRs are always welcome 👍

**Comment by IvanMMM** [comment]
Any updates on this? I can realize it myself, but in this case let's discuss how it will work.
I'm thinking about new collection `changingEmails` with next fields:
`userId` - we'l send it back to user in our callback so user can select user to be updated;
`newEmail` - we'l send it back to user in our callback too;
`token` - to generate/get url link, obviously,
`createdAt` - to let user decide TTL of change email request.

User requests email change, we create new object of emailChangeRequest in our db and send confirmation email. After user clicked on link we use same-as `confirmTempUser` function where we remove user object from our collection and pass values `userId` and `newEmail` to callback and let user decide how is to update his model. Is this Ok?

And I have several questions and I hope you will help me solve it.

1. What should we do if user sends `emailChangeRequest` second time?
2. What if link is outdated and doc is removed from `changingEmails` collecton?
